### ISSUE TITLE
I think your API is down

### ISSUE THREAD

**Issue by victorbutler** [maskaravivek/helium-monitor#4]
I was trying out your project, but it seems to be malfunctioning. Your XHR requests are not receiving good responses. Heroku app might be down.

![image](https://user-images.githubusercontent.com/1063420/124334153-73699580-db53-11eb-9714-a7db53d58565.png)

![image](https://user-images.githubusercontent.com/1063420/124334282-dd823a80-db53-11eb-948f-bd793d9f1411.png)

**Comment by maskaravivek** [comment]
@victorbutler  Thanks for pointing it out. We fixed it a few days back.
