### ISSUE TITLE
idea: add monthly breakdown

### ISSUE THREAD

**Issue by dakky221** [maskaravivek/helium-monitor#5]
Please include the "this month" just like you have "last 7 days" and "last 30 days". 

"this month" would count from 1st to 1st in the actual month and would help get the real balance when more hotspots are shared between people.

**Comment by rsvarma95** [comment]
That would be a good addition. We'll work on it and it should be available with the next release.

**Comment by rsvarma95** [comment]
This functionality has been added in the latest commit.
